<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>

    <p class="ml-10 text-2xl">

        <?php

        if (count($this->resultado) == 0) {
            echo "Búsqueda sin resultados.";
        }
        echo $this->mensaje;
        ?>
    </p>
    <br>

<div class = "mx-5 flex space-x-5">
    <div class=" basis-2/3">
        <table class="mx-auto bg-blue-50 border-separate border-spacing-1 border border-slate-500">
            <thead>
                <tr class="text-blue-900">
                    <th>id</th>
                    <th>Tarea</th>
                    <th>Responsable</th>
                    <th>Estado</th>
                    <th>Inicio</th>
                    <th>Final</th>

                </tr>
            </thead>
        <tbody>
            <?php  
                foreach($this->resultado as $tarea) {
                    echo "<tr class=\"text-blue-800 \">";
                    echo "<td class=\"border border-slate-300\">" . $tarea["id"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["tarea"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["responsable"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["estado"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["inicio"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["fin"] . "</td>";


                    echo '<td class="border border-slate-300">
                            <form action="' . WEB_ROOT . '/modificar" method="POST">
                                <input type="hidden" name="id" value="' . $tarea["id"] . '">
                                    <button type="submit" class="text-red-600">
                                    <img class="size-4 hover:scale-150" src="' . WEB_ROOT . '/images/modificar.png">
                                    </button>
                            </form>
                        </td>';

                    echo '<td class="border border-slate-300">
                            <form action="' . WEB_ROOT . '/conf_eliminar" method="POST">
                                <input type="hidden" name="id" value="' . $tarea["id"] . '">
                                    <button type="submit" class="text-red-600">
                                    <img class="size-4 hover:scale-150" src="' . WEB_ROOT . '/images/borrar.png">
                                    </button>
                            </form>
                        </td>';

            }
            ?>
        </tbody>
        </table>
    </div>


</body>
</html>


