
<div>
<h2 class="ml-20 mr-80 text-5xl text-slate-500 mb-10 font-bold text-center "> LISTA DE TAREAS</h2>
</div>


<div class = "mx-5 flex space-x-5">
    <div class=" basis-2/3 h-96 overflow-auto">
        <table class="mx-auto bg-blue-100 border-separate border-spacing-1 border border-slate-500">
            <thead>
                <tr class="text-blue-900">
                    <th>id</th>
                    <th>Tarea</th>
                    <th>Responsable</th>
                    <th>Estado</th>
                    <th>Inicio</th>
                    <th>Final</th>

                </tr>
            </thead>
        <tbody>
            <?php  

                foreach($this->lista as $tarea) {
                    echo "<tr class=\"text-blue-800 \">";
                    echo "<td class=\"border border-slate-300\">" . $tarea["id"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["tarea"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["responsable"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["estado"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["inicio"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["fin"] . "</td>";

                    echo '<td class="border border-slate-300">
                            <form action="' . WEB_ROOT . '/modificar" method="POST">
                                <input type="hidden" name="id" value="' . $tarea["id"] . '">
                                    <button type="submit" class="text-red-600">
                                    <img class="size-4 hover:scale-150" src="' . WEB_ROOT . '/images/modificar.png">
                                    </button>
                            </form>
                        </td>';

                    echo '<td class="border border-slate-300">
                            <form action="' . WEB_ROOT . '/conf_eliminar" method="POST">
                                <input type="hidden" name="id" value="' . $tarea["id"] . '">
                                    <button type="submit" class="text-red-600">
                                    <img class="size-4 hover:scale-150" src="' . WEB_ROOT . '/images/borrar.png">
                                    </button>
                            </form>
                        </td>';
            }
            ?>
        </tbody>
        </table>
    </div>
    <div class=" mr-5 text-center space-y-5 basis-1/6 text-2xl ">
        <div class="bg-green-200  py-5  rounded-2xl">
            <a href= <?php echo WEB_ROOT . "/agregar" ?> >Agregar tarea</a>
        </div>
        <div class="bg-blue-200  py-5   rounded-2xl">
            <a href= <?php echo WEB_ROOT . "/buscar" ?> >Buscar tarea</a>
        </div>
        <div class="bg-red-400  py-5 rounded-2xl text-xl">
            <a href= <?php echo WEB_ROOT . "/borrar_lista" ?> >Borrar lista</a>
        </div>
        <div class="bg-yellow-100  py-5 rounded-2xl text-xl">
            <a href= <?php echo WEB_ROOT . "/cargar_lista" ?> >Cargar lista de muestra</a>
        </div>
    </div>
</div>
<br><br>
