<h2 class="ml-20 text-5xl  font-bold"> LISTA DE TAREAS</h2>
<br>

<div class = "mx-5 flex space-x-5">
    <div class=" basis-2/3">
        <table class="mx-auto bg-blue-50 border-separate border-spacing-1 border border-slate-500">
            <thead>
                <tr class="text-blue-900">
                    <th>id</th>
                    <th>Tarea</th>
                    <th>Responsable</th>
                    <th>Estado</th>
                    <th>Inicio</th>
                    <th>Final</th>

                </tr>
            </thead>
        <tbody>
            <?php  
                $tareas = new TareasModel();
                $lista = [];
                $lista = $tareas->getToDoList();
                $modificar = WEB_ROOT . "/modificar";
                $eliminar = WEB_ROOT . "/eliminar";
                foreach($lista as $tarea) {
                    echo "<tr class=\"text-blue-800 \">";
                    echo "<td class=\"border border-slate-300\">" . $tarea["id"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["tarea"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["estado"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["responsable"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["inicio"] . "</td>";
                    echo "<td class=\"border border-slate-300\">" . $tarea["fin"] . "</td>";

            }
            ?>
        </tbody>
        </table>
    </div>
    <div class=" mr-5 text-center space-y-10 basis-1/6 text-3xl ">
        <div class="bg-green-200  py-5  rounded-2xl">
            <a href= <?php echo WEB_ROOT . "/agregar" ?> >Agregar</a>
        </div>
        <div class="bg-blue-200  py-5   rounded-2xl">
            <a href= <?php echo WEB_ROOT . "/modificar" ?> >Modificar</a>
        </div>
        <div class="bg-red-200  py-5 rounded-2xl">
            <a href= <?php echo WEB_ROOT . "/eliminar" ?> >Eliminar</a>
        </div>
    </div>
</div>
